= Error Handling

== Background on Mule Error Handling

In Mule 4, the application developer handles _Mule exceptions_, not Java exceptions. Therefore, as an extension developer you should map Java exceptions to Mule errors. ErrorType is the identifier for the Mule error. If a MuleEvent fails it contains an Error object, which contains an ErrorType, a Description. For an example, an `ErrorType` could be `MULE:CONNECTIVITY`

SDK enables the extension developer to declare the *error types* that can be thrown by the extension and where they can be thrown, for example at the operation or configuration levels.
//what are the levels at which the errors can be thrown at runtime
* Map the existing Java exceptions to Mule errors
* Declare which components can throw errors, including the type of the errors

== Declaring Error Types and Where Errors are Thrown

Each error should have an `@ErrorTypes` `ErrorTypeDefinition`. This must be an `enum` class defining the error types.

`@ErrorTypes` are declared at the @Extension level and reference the class with the definition.

`@Throws` defines the `ErrorTypeProvider`, which returns a `Set` of error types definitions which are the values of the `ErrorTypeDefinition` class. @Throws can be applied at the `@Extension`, `@Operations`, and at the methods of the `@Operations`. A Configuration can't thrown an error. A connection exception are automatically exposed as <extension:CONNECTIVITY>, extending the Mule connectivity error type.

The extension developer can inherit an `ErrorType` defined by Mule. For example, an extension can throw a connectivity error that extends from a Mule defined connectivity error.

As a consequence, all the declared errors inside a module would be part of the same namespace, so the module developer should, upon specifying the correct namespace, worry only about the error type.
//assuming module=extension?
//can the Mule error type be customized via the module. Where is a module's namespace identified in the code?

[NOTE]
Example: If the Slack module declares the `NOT_FOUND` error for a certain operation, this will be registered as `SLACK:NOT_FOUND` error.
//all-caps?

The purpose of the restriction on error declaration is to impose a standardized way to expose module errors and also ensure a consistent experience for the developer handling errors in a Mule application. For a module developer, this provides a streamlined development experience. For the Mule app developer, a consistent experience across all modules.

=== @Throws



Deepest @Throws declaration overrides any parent @Throws declaration.

=== Error Type Provider

Must specify the error types that can be thrown.

=== How to Throw an Error

Use a `ModuleException` or when the error is thrown, the error will be reported as <MODULE:UNKNOWN>. The Mule application developer cannot catch an `UNKNOWN` error.

== ModuleException

Can throw anywhere in your module, with the ErrorType you want to throw (that has been defined in your module).
