= To Create a Directory with a Connector
:keywords: file, ftp, connector, operation
:toc:
:toc-title: To Create a Directory

toc::[]

For Anypoint Studio, Design Center:
include::include_link_list.adoc[tags=file-connector]
include::include_link_list.adoc[tags=ftp-connector]

link:about-ftp-connector[FTP] connectors

. After adding the connector to your flow, select the operation.
. Set up or select a configuration for the connector (see link:to-set-up-a-file-connector-config[To set up a File connector]).
. TODO, TODO

// <file:create-directory directoryPath="backup/january_2016" />


[[see_also]]
== See Also
include::include_link_list.adoc[tags=tech-ref-ftp]

////
Parameter Name
Required?
Default Value
Description
directoryPath

===== test case =====
<spring:beans>
    <spring:import resource="file-read-config.xml"/>
</spring:beans>

<flow name="createDirectory">
    <file:create-directory directoryPath="#[directory]"/>
</flow>

Can also be used to create a series of chained directories. For the below example, if the folder `backup` doesn’t exist, it will be created in addition to `january_2016`.

[source,xml,linenums]
----
<file:create-directory directoryPath="backup/january_2016" />
==============

The path to the directory to be created

The above creates a directory. Notice that it can also be used to create a series of chained directories. For example, in the example above, if the backup folder doesn’t exists, it will also be created in order to create the archive one.
////
