= To Delete Email over IMAP or IMAPS
:keywords: email, connector, email, imap
:toc:
:toc-title:

toc::[]

For Anypoint Studio, Design Center: link:email-about-the-email-connector[Email] connector

[[short_description]]
Deletes an email from a mailbox folder based on the ID of the email. Defaults to the inbox folder.

[[delete_email]]
. After adding the *Email* connector to your flow, select the *Delete* operation.
. Set up or select an IMAP or IMAPS configuration for the operation (see link:email-imap-to-set-up[To Set Up an IMAP or IMAPS Email Configuration]).
. If you are deleting the file from a folder other than the inbox, provide the name of the folder, for example, `Drafts`. _TODO, VERIFY VALID VALUES_
. Provide the ID of the email that you want to delete. _TODO, HOW DO THEY GET THE ID? CAN THEY AUTOMATE THIS SOMEHOW? REGEX? REALISTIC USE CASE?_

== Errors
_TODO, error MAPPING_

* EMAIL:RETRY_EXHAUSTED
* EMAIL:ACCESSING_FOLDER
* EMAIL:EMAIL_NOT_FOUND
* EMAIL:CONNECTIVITY

[[see_also]]
== See Also

include::include_link_list.adoc[tags=email-connector]

include::include_link_list.adoc[tags=tech-ref-email]
