= HTTP Connectors
:keywords: anypoint studio, esb, connectors, http, https, http headers, query parameters, rest, raml
:toc:
:toc-title:



toc::[]


HTTP connectors for Mule include:

* *HTTP listener*
* *HTTP requester*
* *Load static resource*
* *Basic auth security filter*

All are accessible from your Mule application design palette, typing "HTTP". The listener and requester require a *connector configuration*. With the connectors you can handle and customize HTTP responses, set up authentication with a *TLS Context* and send customized requests.

=== About HTTP Listener

Use the HTTP listener in the source (left) side of a flow to listen for requests that should trigger a Mule flow, and then return the response to the requester after flow processing.

* link:/mule-user-guide/v/latest/http-listener-reference[HTTP Listener Reference]
// List special configuration procedures from above doc below

=== About HTTP Requester

Use to send requests to a certain address and receive the returned response. Place the HTTP requester in the process (right) side of the flow.

The request will return a `MuleMessage` with specific `HttpResponseAttributes`.

* link:/mule-user-guide/v/latest/http-request-reference[HTTP Requester Reference]
* link:/mule-user-guide/v/3.8/http-listener-connector#mapping-between-http-requests-and-mule-messages[Mapping HTTP Requests to MuleMessage]

// List special configuration procedures from above doc below

=== About Load Static HTTP Resource

Select the `<load-static-resource>` operation and define the required attributes.

link:/load-static-resource-reference[Load Static Resource Reference]

=== About Basic Security Filter

Requires the status code and `headersRef` fields of a error-response-builder to be set as flow variables, so that the filter can set those. This option will allow the gateway to keep applying their basic auth policy in any order.

== HTTP Listener Tasks

=== Route Incoming Requests to HTTP Listeners

* link:/#route-path[Route Requests Based on URI] by setting *Path*.
* Route based on HTTP method be setting the *Allowed Methods* for each listener, `GET`, `POST`, `UPDATE`, etc.

[IMPORTANT]
To host your application on CloudHub, set all listeners' *Host* to `0.0.0.0`.

[[route-path]]
==== Route Requests Based on URI

To route requests to different listeners that trigger different flows, set the *Path* for each listener to a different valid subpath in the domain.

To route to `+http://localhost:8081/employee+` or `+http://localhost:8081/account+`, set up the listeners as follows:

* Set one listener's *Path* to `account` and the other listener's to `employee`
* Set *Host* to `localhost`
* Set *Port* to `8081`


===== Ways to Set the Path

* Wildcards such as * are accepted in paths, for example a *Path* of `/regions/us/prospects` is valid.

[NOTE]
====
Listeners with a more specific path are always given priority in routing.

Given a listener for *Path* `account/\*` and another on `account/*/main-contact`, if a request arrives for `account/mulesoft/main-contact`, it arrives on the listener for `account/*/main-contact`.
====

* Use a variable for a URI parameter like `{accountId}` to use the value of an inbound property `accountId` accessed from Mule Expression Language. `#[message.inboundProperties.'http.uri.params'.accountId]`

=== Implement Basic Authentication when Listening for Responses

//TODO
=== Configure Connection Attributes

Set maximum idle time and connection persistence

=== Generate the HTTP Response

Optionally set up the HTTP response so that it contains the desired body, attachment, headers and status. The response body is generates from the Mule message payload.

==== Generating HTTP Response Body Types

.Response properties for payload of type `Map`
[%header]
|===
|Payload |Response Body |Response Header
|Map |`application/x-www-form-urlencoded` | Content-Type: `application/x-www-form-urlencoded`
|===

.Response properties for Mule Message with Attachments
[%header]
|===
|Payload |Response Body |Response Header
|Not used |`multipart/form-data` | Set the header explicitly
|===

=== Generate HTTP Response Headers

* link:/#set-header-ex[Set Header Explicitly using Properties]
Response headers are generated from outbound properties which the exception of an outbound property named "Connection", "Host", or "Transfer-Encoding".
* link:/#disable-headers[Disable outbound properties as headers] in response
* Set in the Listener Configuration
//TODO confirm

[[set-header-ex]]
==== Set Header Explicitly

* Set a header using the Property Transformer `<set-property>`.
* Use Response Builder to set headers, even dynamically
* Set the HTTP status code and reason phrase using Property Transformer
//TODO confirm how to set headers

[[disable-headers]]
==== Disable Outbound Properties as Headers

In the HTTP Listener properties editor, in the *Response Settings* section, tick the box labeled *Disable Properties*
//TODO confirm

=== Stream HTTP Requests or Responses through Listener

The transfer-encoding header is used to stream data through the HTTP connection so as not to read all into memory.

Transfer-encoding header is used to send the HTTP message body in chunks, saving us from having to know the body length in advance. Each chunk is separated by a predefined line separator, which contains the length of the particular chunk

For streaming using the HTTP Requester, see link:/#stream-requester[How to Stream through Requester]


== HTTP Requester Tasks

=== Send Authenticated Requests

link:/mule-user-guide/v/3.8/authentication-in-http-requests[Authenticated Requests], via *Basic Authentication, Digest and OAuth*

=== Send Multipart HTTP Requests

=== Customize HTTP Requests and Parameters

The HTTP Requester allows you to include the following types of parameters and maps of these:

* query params
* URI params
* headers

*Notes*

* Send form parameters with your request, included in the Mule message payload
* Include attachments in your request by adding an Attachment building block to your flow.
* Customize the body of the request using the `source` and `target` attributes
* For `GET`, `HEAD` and `OPTIONS` methods, override the default empty body. Send a body with a request `sendBodyMode`
* Set headers, URI parameters explicitly or dynamically, using DataWeave language.
* Send form parameters in `POST` request

[[stream-requester]]
=== Stream through the HTTP Requester

* Set the attribute `requestStreamingMode`

=== Disable HTTP Response Body Parsing

//TODO

=== Validate HTTP Responses

//TODO

== Additional Reference

=== Send or Receive HTTPS requests

[NOTE]
Configuration depends on whether you have a HTTP server or client and whether or not you need two-way authentication.

Configure a TLS Context (keystore and/or trust store) to set up HTTPS (see
link:/mule-user-guide/v/3.8/tls-configuration[TLS Configuration]). Setting both a trust store and a key store means having two-way TLS.

*One-way scenarios*

- Server implements *key store* to enforce client authentication
- Client implements *trust store* (JVM's will be used if not provided)

=== Migrate from Mule 3 HTTP Connectors

//TODO

=== Map HTTP Responses to Mule Messages

//TODO

== See Also

* See the link:/mule-user-guide/v/3.8/http-connector-reference[full reference]﻿ for the available XML configurable options in this connector.
