= To Migrate Assets from Exchange 1 to Exchange 2
:keywords: exchange, migrate, migration, exchange 1, exchange 2, anypoint exchange

Anypoint Exchange 2 introduces a new way of working with your assets. Where Exchange 1 is a listing service that only provides links to where assets are stored, Exchange 2 is a package management system that stores assets. 

Migration to Exchange 2 differs by asset type:

[%header%autowidth.spread]
|===
|Asset Type |Migration Approach |Documents
|Connector |Maven Facade Deploy |link:/anypoint-exchange/ex2-maven[To Publish and Deploy Exchange Assets Using Maven] and <<Example: Publish Using the Maven Facade>>
|Example |Maven Facade Deploy |link:/anypoint-exchange/ex2-maven[To Publish and Deploy Exchange Assets Using Maven] and <<Example: Publish Using the Maven Facade>>
|Template |Maven Facade Deploy |link:/anypoint-exchange/ex2-maven[To Publish and Deploy Exchange Assets Using Maven] and <<Example: Publish Using the Maven Facade>>
|WSDL APIs |Manual publish in Exchange |link:/anypoint-exchange/ex2-add-asset[To Add an Asset to Exchange] and <<To Migrate a WSDL>>
|RAML APIs |Publish using Design Center |link:https://beta-anypt.docs-stgx.mulesoft.com/design-center/v/1.0/upload-raml-task[To Upload an Existing RAML File to Exchange] and <<To Migrate a RAML>>
|===	

== Example: Publish Using the Maven Facade

The Maven Facade lets you migrate connectors, examples, or templates. To use this feature, you need to upload the JAR (or zip) file containing your asset and the pom.xml file via the API. For more information, see link:/anypoint-exchange/ex2-maven[To Publish and Deploy Exchange Assets Using Maven].

Add the Maven Facade as a repository in the distribution management section of your project's pom.xml file:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

 <name>Asset name</name>
 <description>Asset description</description>
 <properties>
   <type>connector</type>
 </properties>

[...]
 <distributionManagement>
   <repository>
     <id>Repository</id>
     <name>Corporate Repository</name>
     <url>http://a1aed8de1c2e911e6869912800a68d7d-1180636514.us-east-1.elb.amazonaws.com[a][b]/api/v1/organizations/2559c34c-bbc7-4a5a-b078-bc1154594906/maven</url>
     <layout>default</layout>
   </repository>
 </distributionManagement>
[...]
</project>
----

===Deterimine the Organization ID
You need to find the organization ID for the business group in which you want to install this asset. There are several ways to find the organization ID for a business group. You can use the REST API or anypoint-cli. Here is an example of the anypoint-cli command to find the organization ID of all child business groups. 
[source,linenums]
----
$ anypoint-cli --username exchange2admin --password  TheP@ssWord --organization MuleSoft --environment Sandbox
    _                            _       _   ____  _       _    __                      
   / \   _ __  _   _ _ __   ___ (_)_ __ | |_|  _ \| | __ _| |_ / _| ___  _ __ _ __ ___  
  / _ \ | '_ \| | | | '_ \ / _ \| | '_ \| __| |_) | |/ _` | __| |_ / _ \| '__| '_ ` _ \ 
 / ___ \| | | | |_| | |_) | (_) | | | | | |_|  __/| | (_| | |_|  _| (_) | |  | | | | | |
/_/   \_\_| |_|\__, | .__/ \___/|_|_| |_|\__|_|   |_|\__,_|\__|_|  \___/|_|  |_| |_| |_|
               |___/|_|                                                                   CLI v2.1.0
                                              

Connecting to the Anypoint Platform...
Connected to MuleSoft - Sandbox
> account business-group list
┌────────────────────────────────────────┬───────────────┬────────────────────────────────────────┐
│ Name                                   │ Type          │ Id                                     │
├────────────────────────────────────────┼───────────────┼────────────────────────────────────────┤
│ MuleSoft                               │ Master        │ aa591b71-a6b2-44b3-9167-dbc4dd845d7d   │
├────────────────────────────────────────┼───────────────┼────────────────────────────────────────┤
│ Acme Banking                           │ Business unit │ c0d4986c-5a9b-41b0-9faf-81ebcb9928d4   │
└────────────────────────────────────────┴───────────────┴────────────────────────────────────────┘
> 
----

Here is an example .pom file to add a new Template assest to Exchange. 
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>org.company</groupId>
  <artifactId>template-application</artifactId>
  
  <!-- version must be 1.0.0-SNAPSHOT for the Exchange 2.0 beta -->
  <version>1.0.0-SNAPSHOT</version>

  <name>Template Application</name>
  <description>Description of the template application</description>
  <properties>
  
  <!-- type must be one of template|example|connector -->
    <type>template</type>
  </properties>

  <distributionManagement>
    <repository>
      <id>PrivateExchange</id>
      <name>Private Exchange</name>
      <url>https://maven.anypoint.mulesoft.com/api/v1/organizations/c0d4986c-5a9b-41b0-9faf-81ebcb9928d4/maven/</url>
      <layout>default</layout>
    </repository>
  </distributionManagement>

</project>
----

Create or modify the settings.xml file inside your ~/.m2 folder that holds the settings that the Maven client uses to run. You need to add a server element to configure the credentials for the Exchange Maven Facade repository:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
 <servers>
   <server>
     <id>Repository</id>
     <username>anypointadmin</username>
     <password>anypointadmin</password>
   </server>
 </servers>
</settings>
----

Publish your releases to Exchange using Maven deploy, for example, using the CLI:

`mvn deploy`

=== To Consume with Maven

Add the Maven Facade as a repository in the repositories section and the asset you want to depend on to the dependencies section of your pom.xml file:

[source,xml,linenums]
----
<project xmlns="http://maven.apache.org/POM/4.0.0"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                     http://maven.apache.org/xsd/maven-4.0.0.xsd">
[...]

 <dependencies>
   <dependency>
     <groupId>org.mule.modules</groupId>
     <artifactId>mule-module-sfdc</artifactId>
     <version>8.0.0-SNAPSHOT</version>
   </dependency>
 </dependencies>

[...]

 <repositories>
   <repository>
     <id>Repository</id>
     <name>Corporate Repository</name>
     <url>http://a1aed8de1c2e911e6869912800a68d7d-1180636514.us-east-1.elb.amazonaws.com/api/v1/organizations/2559c34c-bbc7-4a5a-b078-bc1154594906/maven</url>
     <layout>default</layout>
   </repository>
 </repositories>
[...]
</project>
----

== To Migrate a WSDL

. Go to Exchange 1 and download your WSDL file.
. Go to Exchange 2 and click New.
. Select API Spec - WSDL in the types drop-down.
. In the File field, select your WSDL file.
. Fill in the remaining fields.
. Click Create.


== To Migrate a RAML

. Go to the API Manager Portal for the API and export the API Specification as a zip file.
. Go to Design Center API Designer and create a project of type API Specification.
. Import the zip.
. Publish to Exchange 2

