= Before Creating an Extension Project


Effective use of SDK and its documentation requires:

* A working knowledge of Mule, Anypoint Studio and Java development in general.

* Knowledge of the existing connector offering

* Access to a sandbox environment for the target system or source, and documentation of the Web service it exposes.

A general familiarity with the Java language, specifically the use of Java annotations. SDK's functionality is exposed to connector developers through Java annotations that inject code into your connector classes.

The injected code provides the interface between the connector and Mule that would otherwise require each connector developer to include extensive boilerplate code. This documentation explains each SDK-specific annotation in the context of examples. If you are not familiar with annotations, refer to a brief explanation of Java annotations.

== See Also

Consider reviewing the past framework for building extensions for Mule, called link:/anypoint-connector-devkit/v/3.8[DevKit].
