= Intro to Mule SDK
:keywords: devkit, development, features, architecture
:concept:

Create extensions using the *Mule SDK*, the standard framework used to build components, connectors and other extensions for use with Mule 4.

The Extensions API is the mechanism used to "discover" extensions for Mule.

[IMPORTANT]
Use *SDK* to build connectors for Mule 4 or later. Use DevKit to make connectors for Mule 3.5.3 to Mule 3.8.x.

== What is an Extension?

An extension is a module that facilitates predictable interaction between a Mule application and external resources.

SDK facilitates integration with SaaS, web services and other data sources. In Mule 4, extensions that are connectors to SaaS applications are still called *connectors*.

== Development Environment Requirements

Ensure your development environment is equipped with the following:

* Mule 4
* Design Center or Anypoint Studio
* Java 8
* Maven

== Available SDK Annotations

SDK is an annotations-based framework allowing you as the developer to build features. For a complete list of SDK annotations, see the link:/annotation-reference[Annotation Reference].

== How Does Mule Discover an Extension?

*Extensions API* is the set of interfaces and classes that define the contract between an extension and the Mule 4 runtime environment. At deployment of a Mule application, the API handles communication between an SDK-built extension and the Mule runtime, effectively decoupling their respective tasks. The Extensions API has no dependency on Mule core.

=== Extension Code Organization

Extensions are composed of at least one configuration and a set of operations, whose behavior is usually governed by a configuration.

* Configurations and operations must be defined in different classes
* If the extension provides several configurations, each one must be defined in its own class, although all of them will be required to belong to have a common ancestor class and/or implement the same interface when defined at the same level
* Operations can be defined in a more flexible way. They can all be defined in the same class, be spread across several classes, or even have a one operation per class model.

== See Also

* link:/mule-runtime[Mule Runtime]
* link:/connectors[Connectors]
