:toc:               left
:toc-title:         JMS Connector
:toclevels:         2
:last-update-label!:
:docinfo:
:source-highlighter: coderay
:icons: font


= JMS Connector Global Configuration


Every JMS operation that consumes or publishes messages must reference a JMS Config element that handles its general configuration.

When creating a new configuration, the default settings create an Active MQ connection that allows you to messages publish messages and consume messages using an in memory, non-persistent ActiveMQ broker running on `vm://localhost`.

== Global MediaType Configurations

Default values for contentType and encoding can be provided in the General tab. These properties can be overridden by those in specific operations.

Encoding: Defines the encoding of the Message body. Uses Mule’s encoding by default
Content Type: The content type of the Message body.


== Connecting to a Broker

An in-memory connection is provided by default, but for real-world applications you'll likely want to configure something more robust by using the ActiveMQ connection builder, or by providing a fully customizable Generic connection.

=== Common Connection Parameters

[%header,cols="30,70"]
|===
|Field |Description
|Username and Password | The credentials to be used while creating the connection.
|ClientId |The client ID to assign to the connection.
|Caching Strategy | Sets how the Session and Connections created by the factory are handled. Here you can configure the default-caching strategy or disable caching by setting up a no-caching strategy.
|Specification | Which JMS specification to use.
|===


All three JMS specifications (1.0.2b, 1.1 or 2.0) are supported by the connector. Make sure that the underlying broker and client implementations support the selected specification. All other aspects of configuring the connector are identical regardless of what specification you choose, but keep in mind that some other configurations like deliveryDelay are only supported when using the latest version of the specification.



=== Setting up an ActiveMQ Connection

The connector provides a standard way to configure your ActiveMQ connections for the JMS 1.0.2b and 1.1 specifications. For using the 2.0 specification with Apache Artemis, you must set up a Generic Connection.

An ActiveMQ connection supports two mutually exclusive ways of configuring its Connection Factory.

* *Factory Configuration*:
+
This is the method, uses an ActiveMQConnectionFactory or ActiveMQXAConnectionFactory connection.

* *Connection Factory*: (Available in Studio Only)
+
This method allows you to provide a customized connection factory, it uses the generic connection-factory parameter. If you want to use a different ActiveMQ ConnectionFactory, like an ActiveMQSslConnectionFactory, then you can do so by passing in a reference to your custom factory.



== Set up a Generic JMS Connection Provider

If you don’t want to use ActiveMQ, or you want to use a JMS 2.0 feature, then you can configure a custom connection to the broker using the generic-connection. This connection also supports the same common connection parameters, but has a mandatory connection-factory that can be configured in two fashions:

* Use a JNDI based Connection Factory
+
Through this you can use ActiveMQ 2.0.

* Use bean references
+
Any valid javax.jms.ConnectionFactory reference is a valid connectionFactory for your generic connection. All you need to do is to provide a reference to the factory instance.




== Customizing the Consumer global parameters

In the Consumer tab you can set default values to be used on consuming operations. All the properties in the Consumer tab can be overridden by those in specific operations.

For example, you may want to may want to set up your configuration so that all message consuming operations that reference this configuration use the same durable subscription and that they only consume messages flagged with JMSType='DEMO'.


== Customizing the Producer global parameters

In the Producer tab you can set default values to be used on producing operations. All the properties in the Producer tab can be overridden by those in specific operations.

For example, you may want to may want to set up your configuration so that all message producing operations that reference this configuration use persistent delivery.





== Connection Pooling and Caching

Session caching is important for improving the performance of the connection handling, since the creation of sessions, consumers and producers is expensive in terms of processing power for the JMS client.


=== Caching configuration

Connection Factories are wrapped by a default CachingConnectionFactory. If you are providing a custom connection factory that is already performing caching on its own, you should disable caching by setting the Caching Strategy to "No Caching". Otherwise, it’s highly recommended to use the default CachingConnectionFactory.

The caching strategy can be used for caching consumers, producers or both, with a maximum sessionCacheSize.
This session cache size defines the maximum amount of sessions that can be in the pool per session acknowledgement type, so if you want a maximum of 2 sessions to be cached, and you are using Ack modes of AUTO and CLIENT, then up to 4 session can be present in the cache.



== XML Examples


=== Minimal Setup

The example below shows the simplest possible configuration for the JMS Config element.

[source,xml,linenums]
----
<jms:config name="config">
   <jms:active-mq-connection/>
</jms:config>
----

This configuration allows you to publish and


=== Consumer Configuration

The example below includes a `consumer-config`, which adds default settings for all consuming operations that use this configuration.

So for example, if you want to create an application that consumes only the messages flagged with JMSType='DEMO' and always using the same durable subscription for all the consumers, we can add that global behaviour in our config:

[source,xml,linenums]
----
<jms:config name="config">
   <jms:consumer-config selector="JMSType='DEMO'">
       <jms:consumer-type>
          <jms:topic-consumer subscriptionName="GlobalSubscription" isDurable="true"/>
       </jms:consumer-type>
   </jms:consumer-config>
</jms:config>
----

=== Producer Configuration

The example below includes a `produces-config`, which adds default settings for all producing operations that use this configuration.

Every published message using this configuration is handled by the broker as a persistent message. For performance reasons, it also disables the messageID for all the messages produced:

[source,xml,linenums]
----
<jms:config name="config">
   <jms:active-mq-connection/>
   <jms:producer-config disableMessageId="true" persistentDelivery="true"/>
</jms:config>
----

==== Factory Configuration

[source,xml,linenums]
----
<jms:config name="config">
   <jms:active-mq-connection clientId="myConsumerClient">
     <jms:factory-configuration brokerUrl="vm://localhost?broker.useJmx=false" maxRedelivery="3" />
   </jms:active-mq-connection>
</jms:config>
----

==== Generic ActiveMQ Connection Factory (Available in Studio Only)

[source,xml,linenums]
----
<bean id="sslConnectionFactory"
class="org.apache.activemq.ActiveMQSslConnectionFactory">
   <property name="trustStore" value="/path/to/truststore.ts" />
   <property name="trustStorePassword" value="password" />
   <property name="keyStore" value="/path/to/keystore.ks" />
   <property name="keyStorePassword" value="password" />
   <property name="brokerURL" value="ssl://localhost:61616" />
   <property name="userName" value="admin" />
   <property name="password" value="admin" />
</bean>

<jms:config name="config">
    <jms:active-mq-connection connectionFactory="sslConnectionFactory">
</jms:config>
----

=== Using a JNDI based Connection Factory (or How to setup ActiveMQ 2.0)

This example creates a custom ActiveMQ connection factory with JMS 2.0 support using Apache Artemis.

[source,xml,linenums]
----
<jms:config name="config">
   <jms:generic-connection specification="JMS_2_0">
       <jms:connection-factory>
           <jms:jndi-connection-factory connectionFactoryJndiName="ConnectionFactory" lookupDestination="ALWAYS">
               <jms:name-resolver-builder jndiInitialContextFactory="org.apache.activemq.artemis.ActiveMQInitialContextFactory"                   jndiProviderUrl="vm://localhost?broker.persistent=false&amp;broker.useJmx=false">
                   <jms:provider-properties>
                       <jms:provider-property key="queue.jndi-queue-in" value="in.queue"/>
                       <jms:provider-property key="topic.jndi-topic-in" value="in.topic"/>
                   </jms:provider-properties>
               </jms:name-resolver-builder>
           </jms:jndi-connection-factory>
       </jms:connection-factory>
   </jms:generic-connection>
</jms:config>
----

=== Disable Caching


This example sets the Cache Strategy to "No Caching".

[source,xml,linenums]
----
<jms:generic-connection>
   <jms:caching-strategy>
       <jms:no-caching/>
   </jms:caching-strategy>
</jms:generic-connection>
----

== See Also

* link:/connectors/v/latest/jms-about[About JMS Connector]
* link:/connectors/v/latest/jms-technical-ref[JMS Connector Technical Reference]
