:toc:               left
:toc-title:         JMS Connector
:toclevels:         2
:last-update-label!:
:docinfo:
:source-highlighter: coderay
:icons: font

= To Manually Send a JMS Ack

== About Message Acknowledgments

The consumer of a JMS message sends an acknowledgement to the publisher of that message to confirm that the message has been consumed. The sending of acknowledgements can be handled by the JMS Listener or JMS Consume operation that receives the message, or you can configure these so that this action is carried out "manually" by a separate operation on the same flow.

The manual sending of message acknowledgements can be carried by any of these two JMS operations:

* Ack Operation: Performs a single ACK for the message that's being processed. This operation is idempotent, so performing an ACK more than once over the same message doesn't break the execution of the flow.

* Recover Session Operation: Performs a session recover. A session recover automatically redelivers all the consumed messages that have not being acknowledged.


== Manually Send an Ack


To send an acknowledgement responding a message:

. Create a Mule application as a project.

. Add a Listener operation from the JMS Connector to your flow.

. Create a JMS configuration for the connection, leaving all of the fields with their default values.

. Set the Destination to the name of the queue you want to consume messages from.

+
If you want to consume a Topic, change the Consumer Type to Topic.

. Set the Ack Mode to *MANUAL*.

. Add a JMS Ack operation on any point of your flow after the JMS Listener.

+
An acknowledgement is sent only if the flow executes successfully up until the point where you place this Ack operation.
+
You can add a Recover Session operation instead of an Ack operation to send acknowledgements for all consumed messages that haven't been acknowledged.

. In the Ack operation, set Ack Id to reference where the Ack Id value exists in the incoming Mule message. By default, the Ack Id is in an attribute named ackId, which can be referenced through the expression `#[attributes.ackId]`.



== XML Examples

The example below shows a listener that is set to handle acknowledgements manually, followed by an Ack operation that performs the sending of the acknowledgement.


[source,xml,linenums]
----
<jms:listener config-ref="config" destination="${incomingDestination}"
ackMode="MANUAL"/>
<jms:ack ackId="#[attributes.ackId]"/>
----

This second example shows the same listener, with acknowledgements handled by a Recover Session operation instead of an Ack operation.

[source,xml,linenums]
----
<jms:listener config-ref="config" destination="${incomingDestination}"
ackMode="MANUAL"/>
<jms:recover-session ackId="#[attributes.ackId]"/>
----




== See Also

* link:/connectors/v/latest/jms-consume-task[To Consume JMS Messages]

* link:/connectors/v/latest/jms-handle-transactions-about[To Handle Transactions With JMS Operations]

* link:/connectors/v/latest/jms-about[About JMS Connector]
* link:/connectors/v/latest/jms-technical-ref[JMS Connector Technical Reference]
